# which compilers to use for C and C++
set(GATEAU_C_COMPILER clang)
set(GATEAU_CXX_COMPILER clang++)
if (GATEAU_TOOLCHAIN_COMPILER_VERSION)
    string(APPEND GATEAU_C_COMPILER "-${GATEAU_TOOLCHAIN_COMPILER_VERSION}")
    string(APPEND GATEAU_CXX_COMPILER "-${GATEAU_TOOLCHAIN_COMPILER_VERSION}")
endif()

find_program(CMAKE_C_COMPILER NAMES ${GATEAU_C_COMPILER})
find_program(CMAKE_CXX_COMPILER NAMES ${GATEAU_CXX_COMPILER})
