# which compilers to use for C and C++
set(SOCUTE_C_COMPILER gcc)
set(SOCUTE_CXX_COMPILER g++)
if (SOCUTE_TOOLCHAIN_COMPILER_VERSION)
    string(APPEND SOCUTE_C_COMPILER "-${SOCUTE_TOOLCHAIN_COMPILER_VERSION}")
    string(APPEND SOCUTE_CXX_COMPILER "-${SOCUTE_TOOLCHAIN_COMPILER_VERSION}")
endif()

find_program(CMAKE_C_COMPILER NAMES ${SOCUTE_C_COMPILER})
find_program(CMAKE_CXX_COMPILER NAMES ${SOCUTE_CXX_COMPILER})
