########## Globals ##########

# Branch covered by CI
.git-branch: &git-branch master

variables:
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: recursive
    QT_HASH_SEED: 1
    QT_NO_CPU_FEATURE: sse4.2
    BUILD_TYPE: MinSizeRel

########## Templates ##########

# Compilers
.compiler_unix_variables: &compiler_unix_variables
    CMAKE: /opt/Optwares/bin/cmake
    QT_SDKS_PATH: /opt/Qt

.compiler_gcc64_linux: &compiler_gcc64_linux
    tags:
        - linux
    variables: &compiler_gcc64_linux_variables
        <<: *compiler_unix_variables
        CMAKE_TOOLCHAIN: gcc-linux64
        TARGET_HOST: gcc_64

.compiler_clang64_linux: &compiler_clang64_linux
    tags:
        - linux
    variables: &compiler_clang64_linux_variables
        <<: *compiler_unix_variables
        CMAKE_TOOLCHAIN: clang-linux64
        TARGET_HOST: gcc_64

.compiler_mingw_w64_linux: &compiler_mingw_w64_linux
    tags:
        - cross-windows
    variables: &compiler_mingw_w64_linux_variables
        <<: *compiler_unix_variables
        CMAKE_TOOLCHAIN: mingw-win64
        TARGET_HOST: x86_64-w64-mingw32

# Build job
.build: &build
    stage: build
    only:
        - *git-branch
    artifacts:
        name: "${CI_BUILD_NAME}_${CI_PIPELINE_ID}_${CI_BUILD_REF_NAME}"
        expire_in: "1 day"
        paths:
            - build
    script:
        - mkdir build && cd build
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.pasnox.com:9443/so-cute/cmake-modules.git
        - ${CMAKE} -GNinja -DSOCUTE_CI_USER=gitlab-ci-token -DSOCUTE_CI_PASS=${CI_JOB_TOKEN} -DCMAKE_TOOLCHAIN_FILE=cmake-modules/toolchains/${CMAKE_TOOLCHAIN}.cmake -DCMAKE_PREFIX_PATH=${QT_SDKS_PATH}/${QT_VERSION}/${TARGET_HOST} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DSOCUTE_OFFLINE=ON ..
        - ${CMAKE} --build . --target examples

.build_unix: &build_unix
    <<: *build

.build_win: &build_win
    <<: *build

# Linux GCC 64bits build job
.build_gcc64_linux: &build_gcc64_linux
    <<: [ *build_unix, *compiler_gcc64_linux ]

# Linux Clang 64bits build job
.build_clang64_linux: &build_clang64_linux
    <<: [ *build_unix, *compiler_clang64_linux ]

# Linux Mingw 64bits build job
.build_mingw_w64_linux: &build_mingw_w64_linux
    <<: [ *build_unix, *compiler_mingw_w64_linux ]

# Test job
.test: &test
    stage: test
    only:
        - *git-branch
    script:
        - cd build
        - ${CMAKE} --build . --target tests

.test_unix: &test_unix
    <<: *test

.test_win: &test_win
    <<: *test

# Linux GCC 64bits test job
.test_gcc64_linux: &test_gcc64_linux
    <<: [ *test_unix, *compiler_gcc64_linux ]

# Linux Clang 64bits test job
.test_clang64_linux: &test_clang64_linux
    <<: [ *test_unix, *compiler_clang64_linux ]

# Linux Mingw 64bits test job
.test_mingw_w64_linux: &test_mingw_w64_linux
    <<: [ *test_unix, *compiler_mingw_w64_linux ]

# CI Builds

# #### 5.10.0 ####

# Linux GCC 64bits build job
build:gcc64_linux:5.10.0:
    <<: *build_gcc64_linux
    variables:
        <<: *compiler_gcc64_linux_variables
        QT_VERSION: 5.10.0

test:gcc64_linux:5.10.0:
    <<: *test_gcc64_linux
    dependencies:
        - build:gcc64_linux:5.10.0

# Linux Clang 64bits build job
build:clang64_linux:5.10.0:
    <<: *build_clang64_linux
    variables:
        <<: *compiler_clang64_linux_variables
        QT_VERSION: 5.10.0

test:clang64_linux:5.10.0:
    <<: *test_clang64_linux
    dependencies:
        - build:clang64_linux:5.10.0

# Linux Mingw 64bits build job
build:mingw_w64_linux:5.10.0:
    <<: *build_mingw_w64_linux
    variables:
        <<: *compiler_mingw_w64_linux_variables
        QT_VERSION: 5.10.0

test:mingw_w64_linux:5.10.0:
    <<: *test_mingw_w64_linux
    dependencies:
        - build:mingw_w64_linux:5.10.0

# #### 5.11.3 ####

# Linux GCC 64bits build job
build:gcc64_linux:5.11.3:
    <<: *build_gcc64_linux
    variables:
        <<: *compiler_gcc64_linux_variables
        QT_VERSION: 5.11.3

test:gcc64_linux:5.11.3:
    <<: *test_gcc64_linux
    dependencies:
        - build:gcc64_linux:5.11.3

# Linux Clang 64bits build job
build:clang64_linux:5.11.3:
    <<: *build_clang64_linux
    variables:
        <<: *compiler_clang64_linux_variables
        QT_VERSION: 5.11.3

test:clang64_linux:5.11.3:
    <<: *test_clang64_linux
    dependencies:
        - build:clang64_linux:5.11.3

# Linux Mingw 64bits build job
build:mingw_w64_linux:5.11.3:
    <<: *build_mingw_w64_linux
    variables:
        <<: *compiler_mingw_w64_linux_variables
        QT_VERSION: 5.11.3

test:mingw_w64_linux:5.11.3:
    <<: *test_mingw_w64_linux
    dependencies:
        - build:mingw_w64_linux:5.11.3

# #### 5.12.0 ####

# Linux GCC 64bits build job
build:gcc64_linux:5.12.0:
    <<: *build_gcc64_linux
    variables:
        <<: *compiler_gcc64_linux_variables
        QT_VERSION: 5.12.0

test:gcc64_linux:5.12.0:
    <<: *test_gcc64_linux
    dependencies:
        - build:gcc64_linux:5.12.0

# Linux Clang 64bits build job
build:clang64_linux:5.12.0:
    <<: *build_clang64_linux
    variables:
        <<: *compiler_clang64_linux_variables
        QT_VERSION: 5.12.0

test:clang64_linux:5.12.0:
    <<: *test_clang64_linux
    dependencies:
        - build:clang64_linux:5.12.0

# Linux Mingw 64bits build job
build:mingw_w64_linux:5.12.0:
    <<: *build_mingw_w64_linux
    variables:
        <<: *compiler_mingw_w64_linux_variables
        QT_VERSION: 5.12.0

test:mingw_w64_linux:5.12.0:
    <<: *test_mingw_w64_linux
    dependencies:
        - build:mingw_w64_linux:5.12.0
