set(selene_GIT "https://github.com/kmhofmann/selene")
set(selene_CMAKE_ARGS
    -DBUILD_SHARED_LIBS=OFF
    -DSELENE_BUILD_TESTS=OFF
    -DSELENE_BUILD_EXAMPLES=OFF
    -DSELENE_BUILD_BENCHMARKS=OFF
    -DSELENE_USE_OPENCV=OFF
    -DSELENE_USE_LIBJPEG=OFF
    -DSELENE_USE_LIBPNG=ON
    -DSELENE_USE_LIBTIFF=OFF
)
